// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:782286485249:web:01c19ebc6c70a1a2a58d00',
    messagingSenderId: '782286485249',
    projectId: 'airsense-cf390',
    authDomain: 'airsense-cf390.firebaseapp.com',
    storageBucket: 'airsense-cf390.appspot.com',
    measurementId: 'G-2G2DBP8MRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:782286485249:android:2e4f562335b9a548a58d00',
    messagingSenderId: '782286485249',
    projectId: 'airsense-cf390',
    storageBucket: 'airsense-cf390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:782286485249:ios:e52a85b70cd9d302a58d00',
    messagingSenderId: '782286485249',
    projectId: 'airsense-cf390',
    storageBucket: 'airsense-cf390.appspot.com',
    iosBundleId: 'com.example.indoorAirQualityCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:782286485249:ios:546cc55fab65f0b3a58d00',
    messagingSenderId: '782286485249',
    projectId: 'airsense-cf390',
    storageBucket: 'airsense-cf390.appspot.com',
    iosBundleId: 'com.example.indoorAirQualityCheck.RunnerTests',
  );
}
